# Project requirements go here, can be produced with:
#
#   ----------------------------------------------------------------
#    conda export > requirements.yml
#   ----------------------------------------------------------------
